### ISSUE TITLE
Deelvragen beantwoorden

### ISSUE THREAD

**Issue by hesteren** [hesteren/statuspagina-planning#20]
## Task
Deelvragen beantwoorden om vervolgens de hoofdvraag te beantwoorden

- [x] Welke soorten actuele storingen zijn er bekend bij Monta?
- [x] Wat wordt er in de IT wereld verstaan onder effectieve en duidelijke communicatie naar klanten toe?
- [x] Welke statussen zijn het belangrijkst om te delen met klanten van Monta?
- [x] Welke front- en back end technologieën zijn er nodig om een geschikte status applicatie neer te zetten?
